from langchain_experimental.text_splitter import SemanticChunker
from langchain_openai import OpenAIEmbeddings
from langchain_huggingface import HuggingFaceEndpointEmbeddings
from dotenv import load_dotenv
import os

load_dotenv()

embeddings = HuggingFaceEndpointEmbeddings(
    model="sentence-transformers/all-MiniLM-L6-v2",
    huggingfacehub_api_token = os.getenv("HUGGINGFACEHUB_API_TOKEN")
)

text = """
The restoration of ancient architecture offers a unique bridge to the past, allowing modern societies to grasp the craftsmanship and aesthetic values of previous generations. By meticulously preserving stonework, woodwork, and original structural designs, historical sites remain as physical testimonies to human ingenuity. This process often involves a blend of traditional techniques and modern engineering, ensuring that while the building is structurally sound, it retains the authentic spirit and character that defines its historical legacy.

Beyond mere aesthetic value, the maintenance of historical landmarks fosters a sense of collective identity and community heritage within a region. These sites often become focal points for local pride, tourism, and educational exploration, providing a tangible narrative of how a culture has evolved over time. When a community invests in the preservation of its architectural history, it effectively honors its ancestors while providing future generations with a direct connection to the values and stories that shaped their environment.

Quantum computing stands at the precipice of a revolution in digital processing, utilizing the principles of superposition and entanglement to solve problems that would baffle current supercomputers. By operating on qubits rather than traditional bits, these machines can perform complex calculations at exponential speeds, promising breakthroughs in cryptography, material science, and pharmaceutical research. The transition from theory to scalable, fault-tolerant systems remains the primary challenge, but the potential to redefine computational limits continues to drive significant global investment.

The intersection of urban vertical farming and marine ecosystem management represents an unexpected frontier in sustainability. As cities move toward growing crops in high-rise, controlled-environment hydroponic towers to reduce carbon footprints, the nutrient-rich wastewater generated by these systems is being explored for use in restoring coastal seagrass beds. By coupling the rapid food production of modern agriculture with the restoration of ocean biodiversity, researchers hope to create a closed-loop system where terrestrial efficiency actively heals the fragile marine environments decimated by centuries of industrial runoff.

---

Do you find the concept of merging urban agricultural technology with marine restoration an intriguing approach to solving environmental issues?

"""

splitter = SemanticChunker(
    embeddings, 
    breakpoint_threshold_type="standard_deviation",
)

docs = splitter.create_documents([text])

print(docs) 

vector = embeddings.embed_query(text)

print(len(vector))

print(vector[:10])