services:
        app:
                image: structured_output_image:campus

                build:
                        context: .
                        dockerfile: Dockerfile

                command:
                        sh -c "python typed_dict.py && python structured_pydantic.py"

                env_file:
                        - ../.env
                
                stdin_open:
                        true

                tty:
                        true

                container_name:
                        structured_output_container


